var data = {
    "data": {
        "cities": [

            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "海口",
                "ename": "Haikou",
                "districtid": 37,
                "py": "hai kou",
                "firstchar": "H",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
           
            {
                "id": 0,
                "name": "承德",
                "ename": "Chengde",
                "districtid": 135,
                "py": "cheng de",
                "firstchar": "C",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            
            {
                "id": 0,
                "name": "伊春",
                "ename": "Yichun",
                "districtid": 498,
                "py": "yi chun",
                "firstchar": "Y",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "荆门",
                "ename": "Jingmen",
                "districtid": 634,
                "py": "jing men",
                "firstchar": "J",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "眉山",
                "ename": "Meishan",
                "districtid": 914,
                "py": "mei shan",
                "firstchar": "M",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "荔波",
                "ename": "Libo",
                "districtid": 659,
                "py": "li bo",
                "firstchar": "L",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 2374,
                "pname": "黔南"
            },
            {
                "id": 0,
                "name": "黔东南",
                "ename": "Qiandongnan",
                "districtid": 2375,
                "py": "qian dong nan",
                "firstchar": "Q",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "万宁",
                "ename": "Wanning",
                "districtid": 846,
                "py": "wan ning",
                "firstchar": "W",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "泰山",
                "ename": "Taishan",
                "districtid": 6,
                "py": "tai shan",
                "firstchar": "T",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 746,
                "pname": "泰安"
            },
            {
                "id": 0,
                "name": "赤峰",
                "ename": "Chifeng",
                "districtid": 483,
                "py": "chi feng",
                "firstchar": "C",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "荆州",
                "ename": "Jingzhou",
                "districtid": 413,
                "py": "jing zhou",
                "firstchar": "J",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "开平",
                "ename": "Kaiping",
                "districtid": 525,
                "py": "kai ping",
                "firstchar": "K",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 362,
                "pname": "江门"
            },
            {
                "id": 0,
                "name": "平凉",
                "ename": "Pingliang",
                "districtid": 424,
                "py": "ping liang",
                "firstchar": "P",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "通辽",
                "ename": "Tongliao",
                "districtid": 885,
                "py": "tong liao",
                "firstchar": "T",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }


            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            },
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }
            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

            ,
            {
                "id": 0,
                "name": "中卫",
                "ename": "Zhongwei",
                "districtid": 1184,
                "py": "zhong wei",
                "firstchar": "Z",
                "ishot": false,
                "weight": 0,
                "isdomestic": true,
                "ctyid": 110000,
                "ctyname": "中国",
                "pid": 0,
                "pname": ""
            }

        ]
    }
}